<?php
	//$articles = select("PLAYERS","*","ID=4");
	//echo $articles[0]['NAME'];
	//update("PLAYERS", array("NAME"=>"AZDFAZFAZF"), "ID=4");
	clean("PLAYERS");
	insert("PLAYERS", array("NAME"=>"KEVIN","ACTIVE"=>1,"POSITION"=>1,"COLORS"=>"red","GAMES"=>10,"SCORES"=>10,"TOWERS"=>1,"CURRENT_GOLD"=>"10,20,20","CURRENT_SCORES"=>"2,7,9","CURRENT_KILLS"=>"1,3,5","CURRENT_TOWERS"=>"1,2,3","CURRENT_SHOOTS"=>"1,200,200"));
	insert("PLAYERS", array("NAME"=>"MAUREEN","ACTIVE"=>1,"POSITION"=>2,"COLORS"=>"blue","GAMES"=>100,"CURRENT_GOLD"=>"","CURRENT_SCORES"=>"11,17,19","CURRENT_KILLS"=>"","CURRENT_TOWERS"=>"","CURRENT_SHOOTS"=>""));
	insert("PLAYERS", array("NAME"=>"JEAN","ACTIVE"=>1,"POSITION"=>3,"COLORS"=>"YELLOW","GAMES"=>100,"CURRENT_GOLD"=>"180,120,278","CURRENT_SCORES"=>"17,22,10","CURRENT_KILLS"=>"1,15,20","CURRENT_TOWERS"=>"1,2,3","CURRENT_SHOOTS"=>"100,5,2"));
	insert("PLAYERS", array("NAME"=>"MICHELLE","ACTIVE"=>1,"POSITION"=>4,"COLORS"=>"GREEN","GAMES"=>100,"CURRENT_GOLD"=>"0,10,140","CURRENT_SCORES"=>"10","CURRENT_KILLS"=>"1,15,20","CURRENT_TOWERS"=>"1,2,3","CURRENT_SHOOTS"=>"100,5,2"));
	//insert("PLAYERS", array("NAME"=>"ROBERT","ACTIVE"=>0,"POSITION"=>0,"COLORS"=>"RED","GAMES"=>100,"CURRENT_GOLD"=>"210,120,200","CURRENT_SCORES"=>"10","CURRENT_KILLS"=>"1,15,20","CURRENT_TOWERS"=>"1,2,3","CURRENT_SHOOTS"=>"100,5,2"));
?>